## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import json
from pprint import pprint
import requests
from bs4 import BeautifulSoup

## Basic Response from API

In [2]:
api_url = 'http://api.citybik.es/v2/networks/bixi-toronto'
response = requests.get(api_url)
data = response.json()

#pprint(data)

In [5]:
# Exploring the json file

data1 = data['network']

In [6]:
data1.keys()

dict_keys(['company', 'gbfs_href', 'href', 'id', 'location', 'name', 'stations'])

In [7]:
result = data1['stations']

## Creating a DataFrame

In [8]:
city_bike = pd.DataFrame(result)
city_bike

,empty_slots,extra,free_bikes,id,latitude,longitude,name,timestamp
0,2,"{'address': 'Queen St E / Woodward Ave', 'alti...",17,fb337bbed72e2be090071e199899b2be,43.665269,-79.319796,Queen St E / Woodward Ave,2023-12-21T03:42:38.702000Z
1,11,"{'address': 'Primrose Ave / Davenport Rd', 'al...",2,4ff88d5880e71aa40d34cfe5d09b0ca7,43.671420,-79.445947,Primrose Ave / Davenport Rd,2023-12-21T03:42:38.703000Z
2,2,"{'address': 'Queen St. E / Rhodes Ave.', 'alti...",19,a09c67c0b419654d907c9134b108e328,43.666224,-79.317693,Queen St E / Rhodes Ave,2023-12-21T03:42:38.705000Z
3,26,"{'address': 'Bond St / Queen St E', 'altitude'...",9,d6a9daee68070a8b106cfb598d81308c,43.653236,-79.376716,Bond St / Queen St E,2023-12-21T03:42:38.712000Z
4,9,"{'address': 'Church St / Alexander St', 'altit...",15,8f8af40d9388c8a3962559e8681d3db7,43.663722,-79.380288,Church St / Alexander St,2023-12-21T03:42:38.713000Z
...,...,...,...,...,...,...,...,...
772,9,"{'address': '201/207 Princess St', 'altitude':...",8,bf5d4d14e7619f5ff51e264e4095cc4b,43.650298,-79.366485,Princess St / Front St E,2023-12-21T03:42:39.802000Z
773,23,"{'address': 'St George St / Willcocks St', 'al...",0,c53d12128be1f1022c4b78518cca7675,43.662453,-79.397838,St. George St / Willcocks St,2023-12-21T03:42:39.223000Z
774,23,"{'address': '100 Wellington St W ', 'altitude'...",2,d0f019574616cb2bce86924059a4c0f8,43.647043,-79.383141,York St / Wellington St W (2),2023-12-21T03:42:39.058000Z
775,4,"{'address': '200 Parkside Drive', 'altitude': ...",10,479d21ebdac47eb8e30a209268e0bebe,43.644887,-79.456412,High Park Blvd / Parkside Dr,2023-12-21T03:42:39.570000Z
776,15,"{'address': 'Yonge St / Alexander St', 'altitu...",2,9a5a9a00b6f0cb77047f37e70887d891,43.662862,-79.383572,Yonge St / Alexander St - SMART,2023-12-21T03:42:38.808000Z

In [9]:
# Renaming some columns in the DataFrame

city_bike.rename(columns ={ 'name': 'bike_station'}, inplace = True )

In [10]:
# Dropping unwanted columns

city_bike.drop(columns = ['extra', 'timestamp'], axis = 1,inplace = True)

In [11]:
city_bike

,empty_slots,free_bikes,id,latitude,longitude,bike_station
0,2,17,fb337bbed72e2be090071e199899b2be,43.665269,-79.319796,Queen St E / Woodward Ave
1,11,2,4ff88d5880e71aa40d34cfe5d09b0ca7,43.671420,-79.445947,Primrose Ave / Davenport Rd
2,2,19,a09c67c0b419654d907c9134b108e328,43.666224,-79.317693,Queen St E / Rhodes Ave
3,26,9,d6a9daee68070a8b106cfb598d81308c,43.653236,-79.376716,Bond St / Queen St E
4,9,15,8f8af40d9388c8a3962559e8681d3db7,43.663722,-79.380288,Church St / Alexander St
...,...,...,...,...,...,...
772,9,8,bf5d4d14e7619f5ff51e264e4095cc4b,43.650298,-79.366485,Princess St / Front St E
773,23,0,c53d12128be1f1022c4b78518cca7675,43.662453,-79.397838,St. George St / Willcocks St
774,23,2,d0f019574616cb2bce86924059a4c0f8,43.647043,-79.383141,York St / Wellington St W (2)
775,4,10,479d21ebdac47eb8e30a209268e0bebe,43.644887,-79.456412,High Park Blvd / Parkside Dr
776,15,2,9a5a9a00b6f0cb77047f37e70887d891,43.662862,-79.383572,Yonge St / Alexander St - SMART

In [12]:
# Creating a new column in the DataFrame

city_bike['number_of_bikes'] = city_bike['empty_slots'] + city_bike['free_bikes']
city_bike

,empty_slots,free_bikes,id,latitude,longitude,bike_station,number_of_bikes
0,2,17,fb337bbed72e2be090071e199899b2be,43.665269,-79.319796,Queen St E / Woodward Ave,19
1,11,2,4ff88d5880e71aa40d34cfe5d09b0ca7,43.671420,-79.445947,Primrose Ave / Davenport Rd,13
2,2,19,a09c67c0b419654d907c9134b108e328,43.666224,-79.317693,Queen St E / Rhodes Ave,21
3,26,9,d6a9daee68070a8b106cfb598d81308c,43.653236,-79.376716,Bond St / Queen St E,35
4,9,15,8f8af40d9388c8a3962559e8681d3db7,43.663722,-79.380288,Church St / Alexander St,24
...,...,...,...,...,...,...,...
772,9,8,bf5d4d14e7619f5ff51e264e4095cc4b,43.650298,-79.366485,Princess St / Front St E,17
773,23,0,c53d12128be1f1022c4b78518cca7675,43.662453,-79.397838,St. George St / Willcocks St,23
774,23,2,d0f019574616cb2bce86924059a4c0f8,43.647043,-79.383141,York St / Wellington St W (2),25
775,4,10,479d21ebdac47eb8e30a209268e0bebe,43.644887,-79.456412,High Park Blvd / Parkside Dr,14
776,15,2,9a5a9a00b6f0cb77047f37e70887d891,43.662862,-79.383572,Yonge St / Alexander St - SMART,17

In [13]:
# Saving DataFrame to csv

city_bike.to_csv('city_bike.csv',index = False)